
  
language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/multi_fruit_basket_test;

node_js:
  - 12

before_script:
  - psql -c 'create database multi_fruit_basket_test;' -U postgres
  - psql -U postgres -d multi_fruit_basket_test -a -f basket.sql


services:
  - postgresql;